### ISSUE TITLE
Add capability for two-motor scan

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/las-dispersion-scan#10]
## Expected Behavior
The optical setup of these dispersion diagnostics contains two glass wedges. Currently we only scan one wedge. However, both are motorized, and it would dramatically increase the range of the dispersion scan if we could scan both within the same dispersion scan. This is not an immediately needed feature, but a very nice to have one. 

In order to keep this general, it would be good to make this an optional feature. Based on conversations with Ruaridh and Aaron previously, it sounded like they may not always use the exact same optical setup, and may sometimes have just a single motor. 

We can work with Mat Britton, a new laser scientist in the laser ops group, for more specifics about how he would like this to work.

**Comment by slactjohnson** [comment]
Did some more testing with Mat today. Based on his testing he believes that this will be needed sooner rather than later (currently "sooner" means in a week or two). 

In his script-based implementation he moved both wedges at the same time, by the same amount, although in different directions, e.g. the two wedges are pinching together or moving apart. 

With two motors working in tandem, it will probably be required to have an "inversion" flag or similar to account for mechanical setup. We may want to invert the positive direction for one or both of the motors to account for the orientation of the motors versus the wedge direction when installed.

**Comment by klauer** [comment]
We talked a bit about this over zoom. For the coupled motion case, a custom ophyd Device class could be implemented. Docs: https://nsls-ii.github.io/ophyd/positioners.html#pseudopositioner

I think one of our existing classes may already do what's needed: https://github.com/pcdshub/pcdsdevices/blob/master/pcdsdevices/pseudopos.py#L360-L443

```python
       class Parallel(SyncAxis):
           left = Cpt(EpicsMotor, ':01')
           right = Cpt(EpicsMotor, ':02')
```
