### ISSUE TITLE
Problem with Negative Spectrum

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/las-dispersion-scan#13]
## Current Behavior
If the sum of a spectrum is negative, then the scan will hang while waiting for a sum above 1e-6. 

## Possible Solution
Add an `abs()` around this sum, or change how a zero spectrum is detected. Thankfully due to some improvements to the spectrometer IOC, this zero spectrum detection will likely not be needed anymore. 
https://github.com/pcdshub/las-dispersion-scan/blob/master/las_dispersion_scan/dscan.py#L715

## Context
Ran into this while testing something else. Hot fixed as described above in my dev directory where I'm working on the other feature, and it works now.

**Comment by klauer** [comment]
I had never anticipated there would be a negative spectrum - still seems a bit suspect to me, but `np.sum(np.abs(spectrum))` seems appropriate. 

I think it may be good to leave it in regardless of the improvements you mentioned, in case the IOC has yet to initialize that waveform for any reason.

**Comment by slactjohnson** [comment]
It wasn't a huge negative value, usually on the order of -50.0 to -10.0. there was just a small baseline offset (when there is no laser on the spectrometer) so that the sum over the entire spectrum was negative. 
Admittedly, this would only happen when the spectrum is _very_ low, or when testing like I was with no active laser source.
