### ISSUE TITLE
Data Export/Retrieval Updates

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/las-dispersion-scan#18]
## Expected Behavior
From Mat:

"In terms of the data export, all of the currently contained information should stay so that we always have the backup option of preparing the data and retrieving the pulse separate from the program. Specifically: keep the raw motor positions.
We do not need to keep the option of exporting as separate files. NPZ is fine!

The retrieval does not need to happen automatically. This will slow us down sometimes. "Start scan" and "retrieve pulse" could be separate steps (buttons). In this case, "export data" needs to work whether or not we have retrieved the pulse.

Two parameters, "non-linear process" (existing) and "method" (not existing) are important for the retrieval. The non-linear process can be fed directly into the retrieval algorithm. However, the method is used for preparing the data, and depending on the method, other parameters are needed too. For example, in d-scan, we need the material, wedge angle, and motor geometry. It would probably be easiest for us to meet to discuss this, but a specific example for the OPCPA is in the thread of this message."

Description and image from his thread:

"Concerning 2d, here is an example of the processing that I perform for the d-scan of the OPCPA. We need to turn the motor positions into the relative thickness of BK7 that the laser passes through:

parameter_data = 2*(max(scan_positions_motor) - scan_positions_motor)*np.sin(np.pi*wedge_angle/180)

where parameter_data is the relative thickness of glass, and scan_positions_motor  is the readout of the motor positions. The material (BK7) is passed directly to the retriever as a method-specific parameter.

The factor of 2 is because two stages are moving, but the readout position is for a single motor
(max(scan_positions_motor) - scan_positions_motor)  is because the maximum motor position is actually the minimum amount of glass, so this effectively flips the axis

np.sin(np.pi*wedge_angle/180) converts the motor position into the thickness of glass according to the diagram below
Ultimately, this conversion should happen prior to plotting the measured/acquired trace, and different "methods" will have very different steps here. For example, a grating scan (like you did in XCS with Aaron) does not use the wedge angle and material, but it uses the grating separation and incident angle.

![image](https://user-images.githubusercontent.com/29102919/227381704-325aba15-bd6f-4d81-a673-3581873d50e6.png)

## Context
Mat has been using the code for a while and sent me a list of improvements.

**Comment by slactjohnson** [comment]
This would be the second set of issues to tackle; these are more involved, but still well defined.

**Comment by klauer** [comment]
> Specifically: keep the raw motor positions.

I believe this is happening currently. Is there an issue with the data being saved?

**Comment by slactjohnson** [comment]
@brittonm ^

**Comment by klauer** [comment]
OK, I think I've covered the issues - broken out into separate ones and closed by those recent PRs:

> We do not need to keep the option of exporting as separate files. NPZ is fine!
Closed by #24 

> The retrieval does not need to happen automatically. ... "Start scan" and "retrieve pulse" could be separate steps (buttons).

Closed by #25 

If I missed anything in this one, let's open another focused issue on it. Closing...
