### ISSUE TITLE
Remove support for importing and exporting old file formats

### ISSUE THREAD

**Issue by klauer** [pcdshub/las-dispersion-scan#20]
## Expected Behavior
`las-dispersion-scan` can just work with `npz` files for importing and exporting.

## Current Behavior
`las-dispersion-scan` supports saving/loading from old text file formats

## Possible Solution
Remove lower-layer support and GUI elements relating to the old files formats

## Context
Per https://github.com/pcdshub/las-dispersion-scan/issues/18
> We do not need to keep the option of exporting as separate files. NPZ is fine!

**Comment by klauer** [comment]
@slactjohnson @brittonm should we continue to support _importing_ of old .dat files, or can we remove that too?

**Comment by slactjohnson** [comment]
I would suspect not; it's a little strange to retain support for reading a file type but not exporting it, and I don't think any data was recorded in that old file style with the new version of the app. However, @brittonm should have the final say as the owner of this on the laser side.

**Comment by brittonm** [comment]
Agreed! I don't think continued support for reading .dat files is needed.
