### ISSUE TITLE
Write scan parameters to EPICS via ScanStatus device

### ISSUE THREAD

**Issue by klauer** [pcdshub/las-dispersion-scan#3]
## Expected Behavior
Per the ConOps:
```
2.1.1.1. Objective: Make all scan parameters EPICS integrated and archived for later retrieval if desired.
2.1.1.1.1. Scan parameters include: Scan start position, scan end position, scan start and end wavelength, and the number of positions to divide the scan into
```
And:
```
2.1.1.6. Objective: Provide a measurement of the final pulse width, in femtoseconds, as determined by the scan via an archivable EPICS PV
```

## Current Behavior
* A prefix for the scan status is supported at startup
* No _status_ PVs are written to just yet

## Possible Solution
Either:
1. Switch to PyDM spinboxes (I think I'd rather avoid this, because we might not want to _always_ write to PVs)
2. Write when the user clicks "scan" to update all the PVs

And also:
* Write the pulse width, when calculated, to the appropriate PV

**Comment by slactjohnson** [comment]
I think that these requirements can be softened a bit. I think it's worth waiting for more discussion/demonstration with the laser group to see what they think about this. 

My original thought was that this routine would be hosted in an IOC, so you get these requirements nearly for free. With the current direction this is going, I think this bears some re-consideration.

**Comment by slactjohnson** [comment]
Based on our testing and discussion with the laser group, this can be closed. They are (more than) satisfied with the current mode of operation.
